[providers]
python = "3.10"

[phases.build]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app/backend"